"""Flask backend for managing YOLO datasets and albumentations augmentations.

Storage layout (under backend/data):
  data/uploaded/<name>/        # datasets uploaded by the user
  data/augmented/<name>/       # datasets generated by the app
  data/configs.json            # albumentations configurations
  data/augmented.json          # metadata for augmented datasets (source, names)
"""
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
import uuid
import zipfile

import yaml
from flask import Flask, Response, jsonify, request, send_file
from flask_cors import CORS

import augmentations as aug
import inference
import jobs
import training

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
UPLOADED_DIR = os.path.join(DATA_DIR, "uploaded")
AUGMENTED_DIR = os.path.join(DATA_DIR, "augmented")
CONFIGS_FILE = os.path.join(DATA_DIR, "configs.json")
AUG_META_FILE = os.path.join(DATA_DIR, "augmented.json")
TRAININGS_DIR = os.path.join(DATA_DIR, "trainings")
MODELS_DIR = os.path.join(DATA_DIR, "models")
MODELS_FILE = os.path.join(DATA_DIR, "models.json")
INFERENCE_DIR = os.path.join(DATA_DIR, "inference")

for d in (UPLOADED_DIR, AUGMENTED_DIR, TRAININGS_DIR, MODELS_DIR, INFERENCE_DIR):
    os.makedirs(d, exist_ok=True)

# Job state is transient and shared between workers. Keep it on the container's
# local filesystem (not the bind-mounted data volume) so atomic file renames are
# reliably visible across worker processes — a host bind mount on Docker Desktop
# can make cross-process reads flaky.
jobs.configure(os.path.join(tempfile.gettempdir(), "yolo-jobs"))

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"}
BASE_CONFIG_ID = "base"

app = Flask(__name__)
# No hard cap on upload size: real YOLO datasets can be several GB, and a cap
# here would abort the request mid-transfer and surface as "Failed to fetch".
app.config["MAX_CONTENT_LENGTH"] = None
CORS(app)


# --------------------------------------------------------------------------- #
# JSON persistence helpers
# --------------------------------------------------------------------------- #
def _load_json(path, default):
    if not os.path.isfile(path):
        return default
    with open(path, "r", encoding="utf-8") as fh:
        try:
            return json.load(fh)
        except json.JSONDecodeError:
            return default


def _save_json(path, data):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=2)
    os.replace(tmp, path)


def load_configs():
    configs = _load_json(CONFIGS_FILE, [])
    if not any(c["id"] == BASE_CONFIG_ID for c in configs):
        configs.insert(0, {
            "id": BASE_CONFIG_ID,
            "name": "Базовая (без аугментаций)",
            "transforms": [],
            "builtin": True,
            "created_at": time.time(),
        })
        _save_json(CONFIGS_FILE, configs)
    return configs


def load_aug_meta():
    return _load_json(AUG_META_FILE, {})


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def safe_name(name):
    name = os.path.splitext(os.path.basename(name or ""))[0]
    name = re.sub(r"[^A-Za-z0-9_.-]+", "_", name).strip("._")
    return name or "dataset"


def kind_dir(kind):
    if kind == "uploaded":
        return UPLOADED_DIR
    if kind == "augmented":
        return AUGMENTED_DIR
    return None


def is_image(path):
    return os.path.splitext(path)[1].lower() in IMAGE_EXTENSIONS


def find_yaml_member(names):
    candidates = [n for n in names if n.lower().endswith((".yaml", ".yml"))]
    if not candidates:
        return None
    candidates.sort(key=lambda n: (n.count("/"), len(n)))
    return candidates[0]


def validate_label_file(text):
    rows = []
    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 5:
            return False, f"line {lineno}: expected 5 values, got {len(parts)}", rows
        try:
            cls = int(float(parts[0]))
            coords = [float(p) for p in parts[1:]]
        except ValueError:
            return False, f"line {lineno}: non-numeric value", rows
        if cls < 0:
            return False, f"line {lineno}: negative class id {cls}", rows
        for c in coords:
            if not (0.0 <= c <= 1.0):
                return False, f"line {lineno}: coordinate {c} out of [0,1]", rows
        rows.append((cls, coords))
    return True, None, rows


def parse_yaml_config(text):
    cfg = yaml.safe_load(text)
    if not isinstance(cfg, dict):
        raise ValueError("YAML root is not a mapping")
    names = cfg.get("names")
    if isinstance(names, dict):
        names = {int(k): str(v) for k, v in names.items()}
    elif isinstance(names, list):
        names = {i: str(v) for i, v in enumerate(names)}
    else:
        raise ValueError("`names` must be a list or mapping")
    nc = cfg.get("nc", len(names))
    return {"train": cfg.get("train"), "val": cfg.get("val"), "names": names, "nc": int(nc)}


def validate_archive(zf):
    members = [m for m in zf.namelist() if not m.endswith("/")]
    for m in members:
        if m.startswith("/") or ".." in m.replace("\\", "/").split("/"):
            raise ValueError(f"unsafe path in archive: {m}")
    yaml_member = find_yaml_member(members)
    if not yaml_member:
        raise ValueError("no .yaml config found in archive")
    cfg = parse_yaml_config(zf.read(yaml_member).decode("utf-8", "replace"))
    if not any("/images/" in ("/" + m) or m.startswith("images/") for m in members):
        raise ValueError("no `images` directory found in archive")
    if not any("/labels/" in ("/" + m) or m.startswith("labels/") for m in members):
        raise ValueError("no `labels` directory found in archive")
    label_members = [m for m in members if "/labels/" in ("/" + m) and m.endswith(".txt")]
    if not label_members:
        raise ValueError("no .txt label files found under `labels`")
    warnings = []
    for m in label_members:
        ok, err, rows = validate_label_file(zf.read(m).decode("utf-8", "replace"))
        if not ok:
            raise ValueError(f"invalid label file {m}: {err}")
        for cls, _ in rows:
            if cls >= cfg["nc"]:
                warnings.append(f"{m}: class id {cls} >= nc ({cfg['nc']})")
    return cfg, members, warnings[:50]


# --------------------------------------------------------------------------- #
# Statistics
# --------------------------------------------------------------------------- #
def split_of(rel_path):
    low = rel_path.replace("\\", "/").lower()
    for split in ("train", "val", "valid", "test"):
        if f"/{split}/" in "/" + low or f"/{split}." in low or low.startswith(split + "/"):
            return "val" if split == "valid" else split
    return "other"


def label_path_for_image(image_path):
    p = image_path.replace("\\", "/")
    p = re.sub(r"(^|/)images(/)", r"\1labels\2", p, count=1)
    return os.path.splitext(p)[0] + ".txt"


def compute_stats(dataset_dir):
    yaml_path = None
    for root, _dirs, files in os.walk(dataset_dir):
        for f in files:
            if f.lower().endswith((".yaml", ".yml")):
                yaml_path = os.path.join(root, f)
                break
        if yaml_path:
            break

    cfg = {"names": {}, "nc": 0}
    if yaml_path:
        with open(yaml_path, "r", encoding="utf-8", errors="replace") as fh:
            cfg = parse_yaml_config(fh.read())
    names = cfg["names"]

    image_files, label_files = [], []
    for root, _dirs, files in os.walk(dataset_dir):
        for f in files:
            rel = os.path.relpath(os.path.join(root, f), dataset_dir).replace("\\", "/")
            if is_image(rel) and "/images/" in "/" + rel:
                image_files.append(rel)
            elif rel.endswith(".txt") and "/labels/" in "/" + rel:
                label_files.append(rel)

    per_split = {}
    per_class = {int(k): 0 for k in names}
    images_per_class = {int(k): set() for k in names}
    unknown_class = {}
    total_instances = 0

    label_set = set(label_files)
    for img in image_files:
        bucket = per_split.setdefault(
            split_of(img), {"images": 0, "labeled": 0, "background": 0, "instances": 0}
        )
        bucket["images"] += 1
        lbl = label_path_for_image(img)
        if lbl in label_set:
            with open(os.path.join(dataset_dir, lbl), "r", encoding="utf-8", errors="replace") as fh:
                _ok, _err, rows = validate_label_file(fh.read())
            bucket["labeled" if rows else "background"] += 1
            for cls, _coords in rows:
                total_instances += 1
                bucket["instances"] += 1
                if cls in per_class:
                    per_class[cls] += 1
                    images_per_class[cls].add(img)
                else:
                    unknown_class[cls] = unknown_class.get(cls, 0) + 1
        else:
            bucket["background"] += 1

    classes = [
        {"id": cid, "name": names[cid], "instances": per_class.get(cid, 0),
         "images": len(images_per_class.get(cid, set()))}
        for cid in sorted(names)
    ]
    splits = [{"split": s, **per_split[s]} for s in sorted(per_split)]

    return {
        "name": os.path.basename(dataset_dir.rstrip("/\\")),
        "nc": cfg["nc"],
        "num_classes": len(names),
        "total_images": len(image_files),
        "total_label_files": len(label_files),
        "total_instances": total_instances,
        "unknown_class_instances": sum(unknown_class.values()),
        "splits": splits,
        "classes": classes,
    }


def count_images(path):
    total = 0
    for root, _dirs, files in os.walk(path):
        if os.sep + "images" + os.sep in root + os.sep or root.endswith("images"):
            total += sum(1 for f in files if is_image(f))
    return total


# Datasets are immutable once created here, so statistics are computed once and
# cached to a JSON file inside the dataset; later reads are instant.
STATS_CACHE_FILE = ".stats.json"


def _stats_cache_path(dataset_dir):
    return os.path.join(dataset_dir, STATS_CACHE_FILE)


def compute_and_cache_stats(dataset_dir):
    stats = compute_stats(dataset_dir)
    try:
        _save_json(_stats_cache_path(dataset_dir), stats)
    except OSError:
        pass
    return stats


def get_cached_stats(dataset_dir):
    cached = _load_json(_stats_cache_path(dataset_dir), None)
    if isinstance(cached, dict):
        return cached
    return compute_and_cache_stats(dataset_dir)


# --------------------------------------------------------------------------- #
# Dataset routes
# --------------------------------------------------------------------------- #
@app.get("/api/datasets")
def list_datasets():
    meta = load_aug_meta()
    items = []
    for name in sorted(os.listdir(UPLOADED_DIR)):
        full = os.path.join(UPLOADED_DIR, name)
        if os.path.isdir(full):
            items.append({"name": name, "kind": "uploaded", "images": count_images(full)})
    for name in sorted(os.listdir(AUGMENTED_DIR)):
        full = os.path.join(AUGMENTED_DIR, name)
        if os.path.isdir(full):
            m = meta.get(name, {})
            items.append({
                "name": name,
                "kind": "augmented",
                "images": count_images(full),
                "display_name": m.get("display_name", name),
                "source": m.get("source"),
                "config_names": [s.get("name") for s in m.get("configs", [])],
            })
    return jsonify(items)


@app.get("/api/datasets/<kind>/<name>")
def get_dataset(kind, name):
    root = kind_dir(kind)
    if root is None:
        return jsonify({"error": "unknown kind"}), 404
    name = safe_name(name)
    path = os.path.join(root, name)
    if not os.path.isdir(path):
        return jsonify({"error": "dataset not found"}), 404
    stats = get_cached_stats(path)
    if kind == "augmented":
        stats["meta"] = load_aug_meta().get(name)
    return jsonify(stats)


def _run_upload_job(job_id, tmp_path, dest):
    """Validate and extract an uploaded archive, reporting progress to the job."""
    try:
        jobs.update(job_id, message="Проверка архива")
        try:
            zf = zipfile.ZipFile(tmp_path)
        except zipfile.BadZipFile:
            jobs.update(job_id, status="error", error="file is not a valid zip archive")
            return
        with zf:
            try:
                _cfg, _members, warnings = validate_archive(zf)
            except ValueError as exc:
                jobs.update(job_id, status="error", error=f"validation failed: {exc}")
                return

            members = [m for m in zf.infolist() if not m.is_dir()]
            jobs.update(job_id, total=len(members), message="Распаковка", phase="unpack")
            os.makedirs(dest, exist_ok=True)
            done = last = 0
            for m in members:
                zf.extract(m, dest)
                done += 1
                if done - last >= 25:
                    jobs.update(job_id, processed=done)
                    last = done

        # Statistics are computed once here and cached; shown as a plain status
        # (no progress bar) since it is a single pass.
        jobs.update(job_id, processed=len(members),
                    message="Подсчёт статистики", phase="stats")
        stats = compute_and_cache_stats(dest)
        stats["warnings"] = warnings
        jobs.update(job_id, status="done", result=stats)
    except Exception as exc:  # noqa: BLE001
        shutil.rmtree(dest, ignore_errors=True)
        jobs.update(job_id, status="error", error=str(exc))
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass


@app.post("/api/datasets")
def upload_dataset():
    if "file" not in request.files:
        return jsonify({"error": "no file part"}), 400
    file = request.files["file"]
    if not file.filename:
        return jsonify({"error": "empty filename"}), 400
    if not file.filename.lower().endswith(".zip"):
        return jsonify({"error": "only .zip archives are supported"}), 400

    name = safe_name(request.form.get("name") or file.filename)
    dest = os.path.join(UPLOADED_DIR, name)
    if os.path.exists(dest):
        return jsonify({"error": f"dataset '{name}' already exists"}), 409

    # Stream the upload to a temp file on disk instead of reading it all into
    # memory (a multi-GB archive in RAM would OOM-kill the worker). The transfer
    # has finished by the time we get here; unpacking runs in the background so
    # the client can poll extraction progress.
    tmp_dir = os.path.join(DATA_DIR, "_tmp")
    os.makedirs(tmp_dir, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(suffix=".zip", dir=tmp_dir)
    os.close(fd)
    file.save(tmp_path)

    job_id = jobs.create("upload", message="Подготовка")
    threading.Thread(
        target=_run_upload_job, args=(job_id, tmp_path, dest), daemon=True
    ).start()
    return jsonify({"job_id": job_id}), 202


@app.delete("/api/datasets/<kind>/<name>")
def delete_dataset(kind, name):
    root = kind_dir(kind)
    if root is None:
        return jsonify({"error": "unknown kind"}), 404
    name = safe_name(name)
    path = os.path.join(root, name)
    if not os.path.isdir(path):
        return jsonify({"error": "dataset not found"}), 404
    shutil.rmtree(path, ignore_errors=True)
    if kind == "augmented":
        meta = load_aug_meta()
        if name in meta:
            del meta[name]
            _save_json(AUG_META_FILE, meta)
    return jsonify({"ok": True})


def _run_augment_job(job_id, source_dir, dest, folder, source, display_name,
                     snapshots, scope):
    """Generate an augmented dataset in the background, reporting progress."""
    try:
        state = {"t": 0.0}

        def progress(done, total):
            now = time.time()
            if now - state["t"] >= 0.3 or done >= total:
                jobs.update(job_id, processed=done, total=total)
                state["t"] = now

        total = aug.count_images(source_dir, scope) * max(1, len(snapshots))
        jobs.update(job_id, total=total, message="Генерация аугментаций",
                    phase="generate")

        written = aug.generate(source_dir, dest, snapshots, scope=scope,
                               progress=progress)

        meta = load_aug_meta()
        meta[folder] = {
            "display_name": display_name,
            "source": source,
            "configs": snapshots,
            "scope": scope,
            "created_at": time.time(),
            "images": written,
        }
        _save_json(AUG_META_FILE, meta)

        jobs.update(job_id, message="Подсчёт статистики", phase="stats")
        stats = compute_stats(dest)
        stats["meta"] = meta[folder]
        try:
            _save_json(_stats_cache_path(dest), stats)
        except OSError:
            pass
        jobs.update(job_id, status="done", result=stats)
    except Exception as exc:  # noqa: BLE001
        shutil.rmtree(dest, ignore_errors=True)
        jobs.update(job_id, status="error", error=f"augmentation failed: {exc}")


@app.post("/api/datasets/augmented")
def create_augmented():
    if not aug.is_available():
        return jsonify({"error": "albumentations недоступна на сервере"}), 503
    body = request.get_json(silent=True) or {}
    source = safe_name(body.get("source"))
    display_name = (body.get("display_name") or "").strip()
    scope = body.get("scope", "all")
    if scope not in ("all", "train"):
        scope = "all"

    # accept a list of config ids; fall back to single config_id for compatibility
    config_ids = body.get("config_ids")
    if not config_ids and body.get("config_id"):
        config_ids = [body["config_id"]]
    if not config_ids:
        return jsonify({"error": "выберите хотя бы одну конфигурацию"}), 400

    source_dir = os.path.join(UPLOADED_DIR, source)
    if not os.path.isdir(source_dir):
        return jsonify({"error": "source dataset not found"}), 404

    all_configs = {c["id"]: c for c in load_configs()}
    # Snapshot the actual values so the record survives later config deletion.
    snapshots = []
    for cid in config_ids:
        cfg = all_configs.get(cid)
        if cfg is None:
            return jsonify({"error": f"config '{cid}' not found"}), 404
        snapshots.append({
            "config_id": cid,
            "name": cfg["name"],
            "transforms": cfg.get("transforms", []),
        })

    if not display_name:
        names = ", ".join(s["name"] for s in snapshots)
        display_name = f"{source} · {names}"

    folder = safe_name(display_name)
    dest = os.path.join(AUGMENTED_DIR, folder)
    suffix = 1
    while os.path.exists(dest):
        suffix += 1
        folder = f"{safe_name(display_name)}_{suffix}"
        dest = os.path.join(AUGMENTED_DIR, folder)
    os.makedirs(dest, exist_ok=True)

    job_id = jobs.create("augment", message="Подготовка")
    threading.Thread(
        target=_run_augment_job,
        args=(job_id, source_dir, dest, folder, source, display_name, snapshots, scope),
        daemon=True,
    ).start()
    return jsonify({"job_id": job_id}), 202


# --------------------------------------------------------------------------- #
# Augmentation config routes
# --------------------------------------------------------------------------- #
@app.get("/api/aug/transforms")
def list_transforms():
    if not aug.is_available():
        return jsonify({"available": False, "transforms": []})
    return jsonify({"available": True, "transforms": aug.registry_schema()})


@app.get("/api/aug/configs")
def list_configs():
    return jsonify(load_configs())


@app.post("/api/aug/configs")
def create_config():
    body = request.get_json(silent=True) or {}
    name = (body.get("name") or "").strip()
    if not name:
        return jsonify({"error": "name is required"}), 400
    configs = load_configs()
    config = {
        "id": uuid.uuid4().hex[:12],
        "name": name,
        "transforms": body.get("transforms", []),
        "builtin": False,
        "created_at": time.time(),
    }
    configs.append(config)
    _save_json(CONFIGS_FILE, configs)
    return jsonify(config), 201


@app.put("/api/aug/configs/<config_id>")
def update_config(config_id):
    body = request.get_json(silent=True) or {}
    configs = load_configs()
    config = next((c for c in configs if c["id"] == config_id), None)
    if config is None:
        return jsonify({"error": "config not found"}), 404
    if config.get("builtin"):
        return jsonify({"error": "базовую конфигурацию нельзя изменить"}), 400
    if "name" in body and body["name"].strip():
        config["name"] = body["name"].strip()
    if "transforms" in body:
        config["transforms"] = body["transforms"]
    _save_json(CONFIGS_FILE, configs)
    return jsonify(config)


@app.delete("/api/aug/configs/<config_id>")
def delete_config(config_id):
    configs = load_configs()
    config = next((c for c in configs if c["id"] == config_id), None)
    if config is None:
        return jsonify({"error": "config not found"}), 404
    if config.get("builtin"):
        return jsonify({"error": "базовую конфигурацию нельзя удалить"}), 400
    configs = [c for c in configs if c["id"] != config_id]
    _save_json(CONFIGS_FILE, configs)
    return jsonify({"ok": True})


@app.post("/api/aug/preview")
def preview_config():
    if not aug.is_available():
        return jsonify({"error": "albumentations недоступна на сервере"}), 503
    body = request.get_json(silent=True) or {}
    source = safe_name(body.get("source"))
    transforms = body.get("transforms", [])
    source_dir = os.path.join(UPLOADED_DIR, source)
    if not os.path.isdir(source_dir):
        return jsonify({"error": "выберите загруженный датасет для превью"}), 404
    try:
        result = aug.preview(source_dir, transforms, seed=body.get("seed"))
    except ValueError as exc:
        return jsonify({"error": str(exc)}), 400
    return jsonify(result)


@app.get("/api/jobs/<job_id>")
def get_job(job_id):
    job = jobs.get(job_id)
    if job is None:
        return jsonify({"error": "job not found"}), 404
    return jsonify(job)


# --------------------------------------------------------------------------- #
# Model registry
# --------------------------------------------------------------------------- #
def load_models():
    """Built-in architectures plus any user-added model files."""
    custom = _load_json(MODELS_FILE, [])
    return list(training.BUILTIN_MODELS) + custom


@app.get("/api/models")
def list_models():
    models = load_models()
    for m in models:
        m["builtin"] = m["id"] in {b["id"] for b in training.BUILTIN_MODELS}
    return jsonify({"available": training.is_available(), "models": models})


@app.post("/api/models")
def add_model():
    if "file" not in request.files:
        return jsonify({"error": "no file part"}), 400
    file = request.files["file"]
    if not file.filename or not file.filename.lower().endswith((".pt", ".yaml", ".yml")):
        return jsonify({"error": "ожидается файл .pt или .yaml"}), 400

    fname = safe_name(file.filename) + os.path.splitext(file.filename)[1].lower()
    path = os.path.join(MODELS_DIR, fname)
    file.save(path)

    custom = _load_json(MODELS_FILE, [])
    model = {
        "id": uuid.uuid4().hex[:12],
        "name": request.form.get("name") or os.path.basename(file.filename),
        "spec": path,
        "created_at": time.time(),
    }
    custom.append(model)
    _save_json(MODELS_FILE, custom)
    model["builtin"] = False
    return jsonify(model), 201


@app.delete("/api/models/<model_id>")
def delete_model(model_id):
    if model_id in {b["id"] for b in training.BUILTIN_MODELS}:
        return jsonify({"error": "встроенную модель нельзя удалить"}), 400
    custom = _load_json(MODELS_FILE, [])
    model = next((m for m in custom if m["id"] == model_id), None)
    if model is None:
        return jsonify({"error": "model not found"}), 404
    try:
        if model.get("spec") and os.path.isfile(model["spec"]):
            os.remove(model["spec"])
    except OSError:
        pass
    _save_json(MODELS_FILE, [m for m in custom if m["id"] != model_id])
    return jsonify({"ok": True})


# --------------------------------------------------------------------------- #
# Training. Each run executes in its own subprocess (train_runner.py) so it can
# be terminated immediately. Live state is mirrored to a container-local file
# (reliable cross-process reads); a copy is persisted to the data volume.
# --------------------------------------------------------------------------- #
TRAININGS = {}          # id -> last-known state dict (cache)
TRAIN_PROCS = {}        # id -> subprocess.Popen
_STOP_REQUESTED = set()  # ids the user explicitly stopped
_train_lock = threading.Lock()
LIVE_DIR = os.path.join(tempfile.gettempdir(), "yolo-train")
os.makedirs(LIVE_DIR, exist_ok=True)
TRAIN_RUNNER = os.path.join(BASE_DIR, "train_runner.py")


def _run_file(run_id):
    return os.path.join(TRAININGS_DIR, run_id, "run.json")


def _live_file(run_id):
    return os.path.join(LIVE_DIR, run_id + ".json")


def _save_live(state):
    _save_json(_live_file(state["id"]), state)


def _save_run(state):
    os.makedirs(os.path.join(TRAININGS_DIR, state["id"]), exist_ok=True)
    _save_json(_run_file(state["id"]), state)
    _save_json(_live_file(state["id"]), state)


def read_state(run_id):
    """Return the freshest state: live file, then persisted file, then cache."""
    for path in (_live_file(run_id), _run_file(run_id)):
        data = _load_json(path, None)
        if isinstance(data, dict):
            TRAININGS[run_id] = data
            return data
    return TRAININGS.get(run_id)


def _load_runs():
    if not os.path.isdir(TRAININGS_DIR):
        return
    for run_id in os.listdir(TRAININGS_DIR):
        data = _load_json(_run_file(run_id), None)
        if isinstance(data, dict):
            # A run still marked active after a restart never resumed.
            if data.get("status") in ("running", "preparing"):
                data["status"] = "error"
                data["error"] = "прервано перезапуском сервера"
                _save_json(_run_file(run_id), data)
            TRAININGS[run_id] = data


def _run_summary(state):
    return {
        "id": state["id"],
        "status": state["status"],
        "model_name": state.get("model_name"),
        "dataset_name": state.get("dataset_name"),
        "dataset_kind": state.get("dataset_kind"),
        "device": state.get("device", "cpu"),
        "epochs": state.get("epochs"),
        "current_epoch": state.get("current_epoch", 0),
        "has_weights": state.get("has_weights", False),
        "created_at": state.get("created_at"),
        "error": state.get("error"),
    }


def _build_training_yaml(dataset_dir, run_dir):
    """Write a YOLO data.yaml with an absolute path for the given dataset."""
    yaml_path = None
    for root, _dirs, files in os.walk(dataset_dir):
        for f in files:
            if f.lower().endswith((".yaml", ".yml")):
                yaml_path = os.path.join(root, f)
                break
        if yaml_path:
            break
    cfg = {}
    if yaml_path:
        with open(yaml_path, "r", encoding="utf-8", errors="replace") as fh:
            cfg = yaml.safe_load(fh) or {}

    names = cfg.get("names")
    if isinstance(names, dict):
        names = {int(k): str(v) for k, v in names.items()}
    elif isinstance(names, list):
        names = {i: str(v) for i, v in enumerate(names)}
    else:
        names = {}

    train = cfg.get("train") or "images/train"
    val = cfg.get("val") or train
    out = {"path": os.path.abspath(dataset_dir), "train": train, "val": val,
           "names": names}
    out_path = os.path.join(run_dir, "data.yaml")
    with open(out_path, "w", encoding="utf-8") as fh:
        yaml.safe_dump(out, fh, allow_unicode=True, sort_keys=False)
    return out_path


def _monitor(run_id, proc):
    """Wait for a training subprocess and finalize its state."""
    try:
        pgid = os.getpgid(proc.pid)
    except Exception:  # noqa: BLE001
        pgid = None
    proc.wait()
    # Reap any straggler children left in the process group.
    if pgid is not None:
        try:
            os.killpg(pgid, signal.SIGKILL)
        except Exception:  # noqa: BLE001
            pass
    TRAIN_PROCS.pop(run_id, None)
    if run_id not in TRAININGS:
        return  # deleted
    state = read_state(run_id)
    if state is None:
        return
    if state.get("status") in ("preparing", "running"):
        # The process ended without writing a terminal status → it was killed.
        if run_id in _STOP_REQUESTED:
            state["status"] = "stopped"
            state["message"] = "Остановлено пользователем"
        else:
            state["status"] = "error"
            state["error"] = state.get("error") or "процесс обучения завершился неожиданно"
            state["message"] = "Ошибка"
        state["finished_at"] = time.time()
        _save_run(state)
    _STOP_REQUESTED.discard(run_id)


@app.get("/api/devices")
def list_devices():
    info = training.list_devices()
    info["available"] = training.is_available()
    return jsonify(info)


@app.get("/api/trainings")
def list_trainings():
    runs = [read_state(rid) or TRAININGS[rid] for rid in list(TRAININGS)]
    runs.sort(key=lambda s: s.get("created_at", 0), reverse=True)
    return jsonify([_run_summary(s) for s in runs])


@app.get("/api/trainings/<run_id>")
def get_training(run_id):
    state = read_state(run_id)
    if state is None:
        return jsonify({"error": "training not found"}), 404
    return jsonify(state)


# States in which the run is still producing updates.
RUNNING_STATES = {"preparing", "running"}


@app.get("/api/trainings/<run_id>/stream")
def stream_training(run_id):
    """Server-Sent Events: push live run state (epochs + per-batch progress) as
    soon as the training subprocess writes it, so the client never polls."""
    if read_state(run_id) is None:
        return jsonify({"error": "training not found"}), 404

    def gen():
        last = None
        idle = 0
        yield "retry: 2000\n\n"
        while True:
            state = read_state(run_id)
            if state is None:
                break
            payload = json.dumps(state, ensure_ascii=False)
            if payload != last:
                last = payload
                idle = 0
                yield "event: state\ndata: " + payload + "\n\n"
            else:
                idle += 1
                if idle >= 20:  # ~10s without change: keep proxies warm
                    idle = 0
                    yield ": keepalive\n\n"
            if state.get("status") not in RUNNING_STATES:
                yield "event: end\ndata: {}\n\n"
                break
            time.sleep(0.5)

    return Response(gen(), mimetype="text/event-stream", headers={
        "Cache-Control": "no-cache",
        "X-Accel-Buffering": "no",      # disable nginx response buffering
        "Connection": "keep-alive",
    })


@app.post("/api/trainings")
def start_training():
    if not training.is_available():
        return jsonify({"error": "ultralytics недоступна на сервере"}), 503
    body = request.get_json(silent=True) or {}

    kind = body.get("dataset_kind")
    name = safe_name(body.get("dataset_name"))
    root = kind_dir(kind)
    if root is None or not os.path.isdir(os.path.join(root, name)):
        return jsonify({"error": "датасет не найден"}), 404
    dataset_dir = os.path.join(root, name)

    model = next((m for m in load_models() if m["id"] == body.get("model_id")), None)
    if model is None:
        return jsonify({"error": "модель не найдена"}), 404

    device = str(body.get("device") or "cpu")
    if device != "cpu" and not training.list_devices()["cuda_available"]:
        return jsonify({"error": "GPU недоступен на сервере"}), 400

    params = training.filter_params(body.get("params"))
    epochs = int(params.get("epochs", 50))
    params["epochs"] = epochs

    run_id = uuid.uuid4().hex[:12]
    run_dir = os.path.join(TRAININGS_DIR, run_id)
    os.makedirs(run_dir, exist_ok=True)
    data_yaml = _build_training_yaml(dataset_dir, run_dir)

    state = {
        "id": run_id,
        "status": "preparing",
        "message": "Подготовка",
        "model_id": model["id"],
        "model_name": model["name"],
        "dataset_kind": kind,
        "dataset_name": name,
        "device": device,
        "params": params,
        "epochs": epochs,
        "current_epoch": 0,
        "metrics": [],
        "has_weights": False,
        "created_at": time.time(),
        "finished_at": None,
        "error": None,
    }
    with _train_lock:
        TRAININGS[run_id] = state
    _save_run(state)

    proc = subprocess.Popen(
        [
            sys.executable, TRAIN_RUNNER,
            "--run-file", _run_file(run_id),
            "--live-file", _live_file(run_id),
            "--model-spec", model["spec"],
            "--data-yaml", data_yaml,
            "--project", run_dir,
        ],
        # Own process group so we can kill the runner AND any children it spawns.
        start_new_session=True,
    )
    TRAIN_PROCS[run_id] = proc
    threading.Thread(target=_monitor, args=(run_id, proc), daemon=True).start()
    return jsonify({"id": run_id}), 202


def _terminate(run_id, hard=False):
    """Kill the training subprocess and its whole process group (children)."""
    proc = TRAIN_PROCS.get(run_id)
    if not proc or proc.poll() is not None:
        return
    sig = signal.SIGKILL if hard else signal.SIGTERM
    try:
        os.killpg(os.getpgid(proc.pid), sig)
    except Exception:  # noqa: BLE001
        try:
            proc.kill() if hard else proc.terminate()
        except Exception:  # noqa: BLE001
            pass


@app.post("/api/trainings/<run_id>/stop")
def stop_training(run_id):
    if run_id not in TRAININGS:
        return jsonify({"error": "training not found"}), 404
    _STOP_REQUESTED.add(run_id)
    _terminate(run_id)
    state = read_state(run_id)
    if state:
        state["message"] = "Останавливается…"
        _save_live(state)
    return jsonify({"ok": True})


@app.delete("/api/trainings/<run_id>")
def delete_training(run_id):
    if run_id not in TRAININGS and not os.path.isdir(os.path.join(TRAININGS_DIR, run_id)):
        return jsonify({"error": "training not found"}), 404
    _STOP_REQUESTED.add(run_id)
    _terminate(run_id, hard=True)
    TRAININGS.pop(run_id, None)
    TRAIN_PROCS.pop(run_id, None)
    shutil.rmtree(os.path.join(TRAININGS_DIR, run_id), ignore_errors=True)
    try:
        os.remove(_live_file(run_id))
    except OSError:
        pass
    return jsonify({"ok": True})


@app.delete("/api/trainings/<run_id>/weights")
def delete_weights(run_id):
    state = read_state(run_id)
    if state is None:
        return jsonify({"error": "training not found"}), 404
    weights_dir = os.path.join(TRAININGS_DIR, run_id, "train", "weights")
    shutil.rmtree(weights_dir, ignore_errors=True)
    state["has_weights"] = False
    state.pop("weights_path", None)
    _save_run(state)
    return jsonify({"ok": True})


@app.get("/api/trainings/<run_id>/weights")
def download_weights(run_id):
    best = os.path.join(TRAININGS_DIR, run_id, "train", "weights", "best.pt")
    if not os.path.isfile(best):
        return jsonify({"error": "веса не найдены"}), 404
    return send_file(best, as_attachment=True,
                     download_name=f"{run_id}_best.pt")


_load_runs()


# --------------------------------------------------------------------------- #
# Inference (run a trained model over a video). Thread-based; history persisted.
# --------------------------------------------------------------------------- #
INFERENCES = {}          # id -> state
INFER_LIVE_DIR = os.path.join(tempfile.gettempdir(), "yolo-infer")
os.makedirs(INFER_LIVE_DIR, exist_ok=True)
VIDEO_EXTENSIONS = {".mp4", ".mov", ".avi", ".mkv", ".webm", ".m4v"}


def _infer_dir(infer_id):
    return os.path.join(INFERENCE_DIR, infer_id)


def _infer_run_file(infer_id):
    return os.path.join(_infer_dir(infer_id), "run.json")


def _infer_live_file(infer_id):
    return os.path.join(INFER_LIVE_DIR, infer_id + ".json")


def _save_infer(state):
    os.makedirs(_infer_dir(state["id"]), exist_ok=True)
    _save_json(_infer_run_file(state["id"]), state)
    _save_json(_infer_live_file(state["id"]), state)


def _read_infer(infer_id):
    for path in (_infer_live_file(infer_id), _infer_run_file(infer_id)):
        data = _load_json(path, None)
        if isinstance(data, dict):
            INFERENCES[infer_id] = data
            return data
    return INFERENCES.get(infer_id)


def _load_inferences():
    if not os.path.isdir(INFERENCE_DIR):
        return
    for infer_id in os.listdir(INFERENCE_DIR):
        data = _load_json(_infer_run_file(infer_id), None)
        if isinstance(data, dict):
            if data.get("status") == "processing":
                data["status"] = "error"
                data["error"] = "прервано перезапуском сервера"
                _save_json(_infer_run_file(infer_id), data)
            INFERENCES[infer_id] = data


def _infer_summary(state):
    return {
        "id": state["id"],
        "status": state["status"],
        "model_run_id": state.get("model_run_id"),
        "model_name": state.get("model_name"),
        "input_name": state.get("input_name"),
        "created_at": state.get("created_at"),
        "has_output": state.get("has_output", False),
        "total_detections": (state.get("stats") or {}).get("total_detections"),
        "error": state.get("error"),
    }


def _trained_models():
    """Training runs that produced downloadable weights."""
    out = []
    for rid in list(TRAININGS):
        state = read_state(rid) or TRAININGS[rid]
        best = os.path.join(TRAININGS_DIR, rid, "train", "weights", "best.pt")
        if state.get("has_weights") and os.path.isfile(best):
            out.append({
                "run_id": rid,
                "model_name": state.get("model_name"),
                "dataset_name": state.get("dataset_name"),
                "created_at": state.get("created_at"),
                "weights": best,
            })
    out.sort(key=lambda m: m.get("created_at") or 0, reverse=True)
    return out


def _infer_thread(state, weights, input_path, output_path):
    state["status"] = "processing"
    state["message"] = "Обработка видео"
    _save_infer(state)
    last = {"t": 0.0}

    def on_progress(done, total):
        now = time.time()
        if now - last["t"] >= 0.4 or (total and done >= total):
            state["processed_frames"] = done
            state["total_frames"] = total
            _save_infer(state)
            last["t"] = now

    try:
        stats = inference.run(weights, input_path, output_path, on_progress)
        state["stats"] = stats
        state["total_frames"] = stats.get("total_frames")
        state["processed_frames"] = stats.get("processed_frames")
        state["has_output"] = os.path.isfile(output_path)
        state["status"] = "done"
        state["message"] = "Готово"
        state["finished_at"] = time.time()
        _save_infer(state)
    except Exception as exc:  # noqa: BLE001
        state["status"] = "error"
        state["error"] = str(exc)
        state["finished_at"] = time.time()
        _save_infer(state)


@app.get("/api/inference/models")
def inference_models():
    return jsonify({"available": inference.is_available(), "models": _trained_models()})


@app.get("/api/inference")
def list_inferences():
    runs = [_read_infer(i) or INFERENCES[i] for i in list(INFERENCES)]
    runs.sort(key=lambda s: s.get("created_at", 0), reverse=True)
    return jsonify([_infer_summary(s) for s in runs])


@app.get("/api/inference/<infer_id>")
def get_inference(infer_id):
    state = _read_infer(infer_id)
    if state is None:
        return jsonify({"error": "inference not found"}), 404
    return jsonify(state)


@app.post("/api/inference")
def start_inference():
    if not inference.is_available():
        return jsonify({"error": "ultralytics недоступна на сервере"}), 503
    if "file" not in request.files:
        return jsonify({"error": "no file part"}), 400
    file = request.files["file"]
    if not file.filename:
        return jsonify({"error": "empty filename"}), 400
    if os.path.splitext(file.filename)[1].lower() not in VIDEO_EXTENSIONS:
        return jsonify({"error": "ожидается видеофайл"}), 400

    run_id = request.form.get("model_run_id")
    model = next((m for m in _trained_models() if m["run_id"] == run_id), None)
    if model is None:
        return jsonify({"error": "обученная модель не найдена"}), 404

    infer_id = uuid.uuid4().hex[:12]
    d = _infer_dir(infer_id)
    os.makedirs(d, exist_ok=True)
    ext = os.path.splitext(file.filename)[1].lower()
    input_path = os.path.join(d, "input" + ext)
    file.save(input_path)
    output_path = os.path.join(d, "output.mp4")

    state = {
        "id": infer_id,
        "status": "processing",
        "message": "Подготовка",
        "model_run_id": run_id,
        "model_name": model["model_name"],
        "dataset_name": model["dataset_name"],
        "input_name": file.filename,
        "input_ext": ext,
        "total_frames": 0,
        "processed_frames": 0,
        "has_output": False,
        "stats": None,
        "created_at": time.time(),
        "finished_at": None,
        "error": None,
    }
    INFERENCES[infer_id] = state
    _save_infer(state)

    threading.Thread(
        target=_infer_thread, args=(state, model["weights"], input_path, output_path),
        daemon=True,
    ).start()
    return jsonify({"id": infer_id}), 202


@app.delete("/api/inference/<infer_id>")
def delete_inference(infer_id):
    if infer_id not in INFERENCES and not os.path.isdir(_infer_dir(infer_id)):
        return jsonify({"error": "inference not found"}), 404
    INFERENCES.pop(infer_id, None)
    shutil.rmtree(_infer_dir(infer_id), ignore_errors=True)
    try:
        os.remove(_infer_live_file(infer_id))
    except OSError:
        pass
    return jsonify({"ok": True})


@app.get("/api/inference/<infer_id>/video")
def inference_video(infer_id):
    path = os.path.join(_infer_dir(infer_id), "output.mp4")
    if not os.path.isfile(path):
        return jsonify({"error": "видео не найдено"}), 404
    return send_file(path, mimetype="video/mp4", conditional=True)


@app.get("/api/inference/<infer_id>/input")
def inference_input(infer_id):
    state = _read_infer(infer_id)
    if state is None:
        return jsonify({"error": "inference not found"}), 404
    path = os.path.join(_infer_dir(infer_id), "input" + state.get("input_ext", ""))
    if not os.path.isfile(path):
        return jsonify({"error": "видео не найдено"}), 404
    return send_file(path, as_attachment=True,
                     download_name=state.get("input_name", "input"))


_load_inferences()


@app.get("/api/health")
def health():
    return jsonify({
        "status": "ok",
        "albumentations": aug.is_available(),
        "ultralytics": training.is_available(),
    })


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
