/* Static design prototype. Everything below is local demo state; no network/API writes. */
const params=new URLSearchParams(location.search);
let layout=['a','b','c'].includes(params.get('layout'))?params.get('layout'):'a';
let palette=['graphite','slate','paper','signal','neutral'].includes(params.get('palette'))?params.get('palette'):'graphite';
let frame=284, tool='select', selected=0, activeClass=0, tab='tracks', uiState='ready', zoom=1, pan={x:0,y:0}, outlines=true, playTimer=null, toastTimer;
const LAST=750;
const classData=[{name:'narrow-grab-closed',short:'Захват',color:'#72BCFF'},{name:'wood-sleeper',short:'Шпала',color:'#FFCC80'},{name:'rail',short:'Рельс',color:'#B7B7F0'},{name:'barrel',short:'Бочка',color:'#8BDCBA'}];
let shapes=[{id:1,ci:0,x:.535,y:.33,w:.209,h:.377,keys:[38,142,284,530,705],interpolate:true,step:5,start:38,end:705,hidden:false},{id:2,ci:1,x:.628,y:.598,w:.075,h:.25,keys:[68,284,462,684],interpolate:true,step:5,start:68,end:684,hidden:false}];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tools=[['select','V','Выбор'],['box','B','Бокс'],['polygon','P','Контур'],['track','T','Трек'],['auto','A','SAM2']];
document.documentElement.dataset.palette=palette;
document.getElementById('app').innerHTML=`
<div class="review-bar"><a href="index.html">← Все макеты</a><label>Компоновка <select id="layout"><option value="a">A · Инспектор справа</option><option value="b">B · Панель слева</option><option value="c">C · Нижняя панель</option></select></label><label>Палитра <select id="palette"><option value="neutral">Нейтральная схема</option><option value="graphite">Графит и мята</option><option value="slate">Сланец и голубой</option><option value="paper">Светлый и синий</option><option value="signal">Серый и кармин</option></select></label><label>Состояние <select id="state"><option value="ready">Рабочее</option><option value="loading">Кадр готовится</option><option value="error">Ошибка кадра</option><option value="readonly">Только просмотр</option><option value="empty">Нет объектов</option></select></label><span class="review-hint">Макет со статичным кадром</span></div>
<header class="app-head"><a href="index.html" class="brand"><span class="mark">М</span>Магистраль ML</a><div class="crumb"><small>Варан / Таски / Демонстрация видеоразметки</small><b>Работа захвата <span class="muted">/ камера 008</span></b></div><div class="spacer"></div><span class="saved" id="save-status">Демо сохранено</span><button id="help">Справка <kbd>?</kbd></button><a href="index.html" title="Вернуться к выбору компоновки">Выйти ↗</a></header>
<main class="workspace layout-${layout}" id="workspace">
<nav class="tools" aria-label="Инструменты разметки">${tools.map(([id,key,name])=>`<button class="tool ${id==='select'?'on':''}" data-tool="${id}" ${id!=='select'?'data-edit':''} title="${name} (${key})" aria-label="${name} (${key})" aria-pressed="${id==='select'}"><strong>${key}</strong><span>${name}</span></button>`).join('')}<div class="tool-sep"></div><button class="tool" id="zoom-in" title="Приблизить" aria-label="Приблизить"><strong>+</strong><span>Зум</span></button><button class="tool" id="zoom-out" title="Отдалить" aria-label="Отдалить"><strong>−</strong><span>Зум</span></button><button class="tool" id="fit" title="Вписать кадр (0)" aria-label="Вписать кадр (0)"><strong>0</strong><span>Вписать</span></button><select class="class-compact" id="compact-class" aria-label="Класс для новых объектов">${classData.map((c,i)=>`<option value="${i}">${c.name}</option>`).join('')}</select></nav>
<section class="viewport" aria-label="Кадр и разметка"><div class="scene-meta"><span>Камера 008</span><span class="source-dim num">1920 × 1400</span><div class="right"><span class="num" id="zoom-value">100%</span><button id="toggle-labels" aria-pressed="true">Разметка</button></div></div><div class="stage" id="stage"><div class="media-frame" id="media-frame"><canvas id="frame-canvas" width="1920" height="1400" role="img" aria-label="Настоящий кадр из датасета Варан: захват держит деревянную шпалу"></canvas></div><svg id="annotation-layer" class="annotation-layer" aria-label="Демонстрационная разметка"></svg><div id="state-shield" class="state-shield" hidden></div></div><div class="sam-actions" id="sam-actions"><span>Пример результата SAM2</span><div class="spacer"></div><button class="primary" id="commit-auto">Закрепить <kbd>Пробел</kbd></button><button id="cancel-auto">Отменить <kbd>Esc</kbd></button></div><div class="scene-footer"><span id="tool-hint">Выбор объекта · протяжка для панорамы</span><span class="right">Колесо: масштаб &nbsp; <kbd>0</kbd> вписать</span></div></section>
<aside class="inspector" aria-label="Классы и объекты"><div class="panel-title"><h2>Классы</h2><span>4 в примере</span></div><section class="classes"><input id="class-search" type="search" placeholder="Найти класс…" aria-label="Найти класс"><div class="class-list" id="class-list"></div></section><div class="tabs" role="tablist" aria-label="Тип объектов"><button role="tab" id="tab-tracks" aria-selected="true" class="on">Треки <span id="track-count">2</span></button><button role="tab" id="tab-singles" aria-selected="false">Одиночные</button></div><div class="object-list" id="object-list"></div><section class="properties" id="properties"></section></aside>
<section class="timeline" aria-label="Таймлайн объектов"><div class="transport"><button id="prev" title="Кадр назад (←)" aria-label="Кадр назад">←</button><button id="play" title="Демонстрация движения указателя (Пробел)" aria-label="Запустить демонстрацию">Играть</button><button id="next" title="Кадр вперёд (→)" aria-label="Кадр вперёд">→</button><label class="frame-counter">Кадр <input id="frame-number" type="number" min="0" max="750" value="284" aria-label="Номер кадра"> <span class="muted">/ 750</span></label><select id="speed" aria-label="Скорость"><option value=".25">¼×</option><option value=".5">½×</option><option value="1" selected>1×</option><option value="2">2×</option></select><select class="quality" id="quality" aria-label="Качество кадра"><option>Исходное</option><option>1080p</option><option>720p</option><option>480p</option></select></div><div class="lanes"><div class="lane-row"><span class="muted">Дорожки объектов</span><div class="ruler" id="ruler"><span>0</span><span>150</span><span>300</span><span>450</span><span>600</span><span>750</span><input id="scrub" type="range" min="0" max="750" value="284" aria-label="Перейти к кадру"></div><span class="lane-status">Кадр</span></div><div id="lane-rows"></div><div class="lane-footer"><span>Ромб: ключ</span><span>Штриховка: заслонение</span><span id="time-value" class="num">00:11.360</span><span>Статичный кадр, демонстрационный тайминг</span></div></div></section>
</main><footer class="app-status"><span id="mode-status">Режим: разметка</span><span id="selection-status">Выбран трек 01</span><span class="right">Макет / локальные изменения / без записи в проект</span></footer><div role="status" class="toast" id="toast" hidden></div>
<dialog id="help-dialog"><header><h2>Управление макетом</h2><button id="close-help" aria-label="Закрыть справку">Закрыть</button></header><p>Это автономный макет на одном настоящем кадре. Изменения разметки и времени демонстрационные. Исходные данные и сервер не подключены.</p><dl><dt>V / B / P / T / A</dt><dd>Выбор инструмента. Бокс и трек можно нарисовать протяжкой; полигон показан как выбранный режим.</dd><dt>Колесо / + / −</dt><dd>Масштаб кадра и синхронное положение разметки.</dd><dt>Протяжка / 0</dt><dd>Панорама в режиме выбора / вписать кадр.</dd><dt>← / → / Пробел</dt><dd>Сдвиг и движение указателя времени. Фотография остаётся той же.</dd><dt>K</dt><dd>Добавить демонстрационный ключ выбранному треку.</dd><dt>1–4 / Delete</dt><dd>Активный класс / удалить выбранный демо-объект.</dd></dl><p>Жесты сложных интервалов, сегментация SAM2, сохранение на сервере и выгрузка будут сохранены при согласованном внедрении. Их размещение зафиксировано на странице аудита.</p><a href="audit.html">Аудит и карта функций ↗</a></dialog>`;
const $=id=>document.getElementById(id);
const cleanButton=document.createElement('button');cleanButton.id='clean-view';cleanButton.textContent='Чистый макет';cleanButton.title='Убрать строку выбора. F2 вернёт её.';document.querySelector('.review-bar').append(cleanButton);cleanButton.onclick=()=>{document.body.classList.add('clean-view');requestAnimationFrame(fitMedia);toast('Строка выбора скрыта. Нажмите F2, чтобы вернуть её.')};window.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();document.body.classList.toggle('clean-view');requestAnimationFrame(fitMedia)}});
$('layout').value=layout;$('palette').value=palette;
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4300)}
function locked(){return ['loading','error','readonly'].includes(uiState)}
function updateUrl(){const url=new URL(location.href);url.searchParams.set('layout',layout);url.searchParams.set('palette',palette);try{history.replaceState(null,'',url)}catch{}}
$('layout').onchange=e=>{layout=e.target.value;$('workspace').className=`workspace layout-${layout}`;updateUrl();requestAnimationFrame(fitMedia)};
$('palette').onchange=e=>{palette=e.target.value;document.documentElement.dataset.palette=palette;updateUrl();renderShapes()};
function renderClasses(){const query=$('class-search').value.toLowerCase().trim();$('class-list').innerHTML=classData.map((c,i)=>({c,i})).filter(({c})=>c.name.includes(query)||c.short.toLowerCase().includes(query)).map(({c,i})=>`<button class="class-option ${activeClass===i?'on':''}" data-class="${i}" aria-pressed="${activeClass===i}"><i class="class-dot" style="--class-color:${c.color}"></i>${esc(c.name)}<kbd>${i+1}</kbd></button>`).join('')||`<div class="no-class">Класс не найден. <button id="create-class">Создать в макете</button></div>`;document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>chooseClass(Number(b.dataset.class)));if($('create-class'))$('create-class').onclick=()=>toast('Создание класса предусмотрено. Макет не меняет словарь проекта.');}
function chooseClass(i){activeClass=i;$('compact-class').value=i;renderClasses();toast(`Класс для новых объектов: ${classData[i].name}`)}
$('class-search').oninput=renderClasses;$('compact-class').onchange=e=>chooseClass(Number(e.target.value));
function visibleShapes(){return uiState==='empty'?[]:shapes}
function renderObjects(){const items=visibleShapes();$('track-count').textContent=items.length;$('object-list').innerHTML=tab==='singles'?'<div class="empty-objects">На кадре нет одиночных объектов. Инструмент «Бокс» создаёт объект на одном кадре; «Трек» ведёт его во времени.</div>':items.length?items.map((s,i)=>`<button class="object-row ${selected===i?'on':''}" data-object="${i}" aria-pressed="${selected===i}"><i class="class-dot" style="--class-color:${classData[s.ci].color}"></i><span class="name">${classData[s.ci].short}<small>${s.keys.length} ключей · ${s.start}–${s.end}</small></span><span class="object-id">${String(s.id).padStart(2,'0')}</span></button>`).join(''):'<div class="empty-objects">Объектов пока нет. Выберите «Трек» и обведите объект на кадре.</div>';document.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>pick(Number(b.dataset.object)));renderProperties();renderLanes();renderShapes();}
function pick(i){selected=i;tab='tracks';setTab(tab);$('selection-status').textContent=`Выбран трек ${String(shapes[i]?.id||1).padStart(2,'0')}`;}
function setTab(next){tab=next;for(const t of ['tracks','singles']){$('tab-'+t).classList.toggle('on',t===tab);$('tab-'+t).setAttribute('aria-selected',String(t===tab))}renderObjects()}
$('tab-tracks').onclick=()=>setTab('tracks');$('tab-singles').onclick=()=>setTab('singles');
function renderProperties(){const s=visibleShapes()[selected];if(!s||tab==='singles'){$('properties').innerHTML='<p class="prop-note">Выберите трек, чтобы изменить свойства.</p>';return}const dis=locked()?'disabled':'';$('properties').innerHTML=`<h3>Свойства трека <span>${String(s.id).padStart(2,'0')}</span></h3><div class="property-fields"><label class="prop-row"><span>Интерполяция</span><input id="interpolate" type="checkbox" ${s.interpolate?'checked':''} ${dis}></label><label class="prop-row"><span>Шаг выгрузки</span><input id="export-step" type="number" min="1" max="750" value="${s.step}" ${dis}></label><div class="prop-row"><span>Интервал</span><span class="value">${s.start} → ${s.end}</span></div></div><button class="primary" id="add-key" ${dis}>Добавить ключ <span class="num">K</span></button><p class="prop-note">${esc(classData[s.ci].name)}<br>Рамка между ключами ${s.interpolate?'интерполируется':'не интерполируется'}.</p><details class="more-actions"><summary>Действия с треком</summary><button id="end-track" ${dis}>Завершить здесь</button><button id="hide-track" ${dis}>${s.hidden?'Показать':'Заслонить'} объект</button><button id="delete-key" ${dis}>Удалить ключ</button><button class="danger" id="delete-track" ${dis}>Удалить трек</button></details>`;$('interpolate').onchange=e=>{s.interpolate=e.target.checked;renderProperties()};$('export-step').onchange=e=>{s.step=Math.max(1,Math.min(750,Number(e.target.value)||1));e.target.value=s.step};$('add-key').onclick=addKey;$('end-track').onclick=()=>{s.end=Math.max(s.start,frame);renderObjects();toast('Конец демо-трека установлен на текущий кадр.')};$('hide-track').onclick=()=>{s.hidden=!s.hidden;renderObjects()};$('delete-key').onclick=()=>{s.keys=s.keys.filter(k=>k!==frame);renderObjects();toast('Ключ текущего кадра удалён, если он был в демо-треке.')};$('delete-track').onclick=deleteTrack;}
function addKey(){if(locked())return;const s=shapes[selected];if(!s||uiState==='empty')return;if(!s.keys.includes(frame))s.keys.push(frame);renderObjects();toast(`Демо-ключ добавлен: кадр ${frame}.`)}
function deleteTrack(){if(locked())return;shapes.splice(selected,1);selected=Math.max(0,selected-1);renderObjects();toast('Объект удалён только из макета. Перезагрузка восстановит пример.')}
function renderLanes(){$('lane-rows').innerHTML=visibleShapes().map((s,i)=>`<div class="lane-row ${selected===i?'selected':''}"><button class="lane-label" data-lane-pick="${i}"><i class="class-dot" style="--class-color:${classData[s.ci].color}"></i>${classData[s.ci].short} <span class="num">${String(s.id).padStart(2,'0')}</span></button><div class="lane-track" data-lane="${i}" style="--class-color:${classData[s.ci].color}" aria-label="Дорожка ${classData[s.ci].short}"><span class="lane-life" style="left:${s.start/LAST*100}%;width:${(s.end-s.start)/LAST*100}%"></span>${i===1||s.hidden?'<span class="occlusion"></span>':''}${s.keys.map(k=>`<span class="key" style="left:${k/LAST*100}%"></span>`).join('')}<span class="needle" style="left:${frame/LAST*100}%"></span></div><span class="lane-status">${s.hidden?'Скрыт':s.keys.includes(frame)?'Ключ':'Между'}</span></div>`).join('');document.querySelectorAll('[data-lane-pick]').forEach(b=>b.onclick=()=>pick(Number(b.dataset.lanePick)));document.querySelectorAll('[data-lane]').forEach(el=>{el.onclick=e=>{const r=el.getBoundingClientRect();setFrame(Math.round((e.clientX-r.left)/r.width*LAST))};el.oncontextmenu=e=>{e.preventDefault();pick(Number(el.dataset.lane));const d=document.querySelector('.more-actions');if(d)d.open=true;toast('Действия дорожки доступны в инспекторе выбранного трека.')}})}
function setFrame(n){frame=Math.max(0,Math.min(LAST,Math.round(Number(n)||0)));$('frame-number').value=frame;$('scrub').value=frame;$('time-value').textContent=`00:${String(Math.floor(frame/25)).padStart(2,'0')}.${String(frame%25*40).padStart(3,'0')}`;renderLanes()}
$('frame-number').onchange=e=>setFrame(e.target.value);$('scrub').oninput=e=>setFrame(e.target.value);$('prev').onclick=()=>setFrame(frame-1);$('next').onclick=()=>setFrame(frame+1);
function stopPlay(){clearInterval(playTimer);playTimer=null;$('play').textContent='Играть';$('play').setAttribute('aria-label','Запустить демонстрацию')}
function togglePlay(){if(playTimer){stopPlay();return}if(locked())return;$('play').textContent='Пауза';$('play').setAttribute('aria-label','Остановить демонстрацию');toast('Движется только указатель времени. Кадр в макете статичный.');playTimer=setInterval(()=>{if(frame>=LAST){stopPlay();return}setFrame(frame+Math.max(1,Math.round(4*Number($('speed').value))))},160)}
$('play').onclick=togglePlay;$('quality').onchange=()=>toast('В макете используется исходный кадр. В приложении качество будет менять декодированный bitmap с сохранением координат.');
function chooseTool(id){if(locked()&&id!=='select')return;tool=id;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('on',b.dataset.tool===id);b.setAttribute('aria-pressed',String(b.dataset.tool===id))});$('tool-hint').textContent={select:'Выбор объекта · протяжка для панорамы',box:'Протяните рамку на кадре: демонстрационная фигура',track:'Протяните рамку: демонстрационный трек',polygon:'Контур: показан режим инструмента, вершины в макете не редактируются',auto:'SAM2: демонстрационное состояние результата'}[id];$('stage').style.cursor=id==='select'?'grab':'crosshair';$('sam-actions').classList.toggle('visible',id==='auto');requestAnimationFrame(fitMedia);}
for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>chooseTool(b.dataset.tool);
$('commit-auto').onclick=()=>{chooseTool('select');toast('Демонстрация подтверждения. Модель SAM2 не запускалась.')};$('cancel-auto').onclick=()=>chooseTool('select');
$('state').onchange=e=>setState(e.target.value);
function setState(value){uiState=value;stopPlay();$('workspace').classList.toggle('locked',locked());$('mode-status').textContent=value==='readonly'?'Режим: только просмотр':value==='loading'?'Подготовка кадра: правка недоступна':value==='error'?'Ошибка кадра: повторите загрузку':'Режим: разметка';$('save-status').textContent=value==='readonly'?'Разметка закрыта':'Демо сохранено';const shield=$('state-shield');shield.hidden=!['loading','error'].includes(value);shield.innerHTML=value==='loading'?'<b>Подготавливаем кадр</b><span>Разметка станет доступна после показа нужного кадра.</span>':value==='error'?'<b>Не удалось загрузить кадр</b><span>Положение разметки сохранено в текущем макете.</span><button id="retry-frame">Повторить</button>':'';if($('retry-frame'))$('retry-frame').onclick=()=>{$('state').value='ready';setState('ready')};for(const b of document.querySelectorAll('[data-edit]'))b.disabled=locked();$('play').disabled=locked();if(locked())chooseTool('select');renderObjects();}
// Match the original editor contract: source frame transforms; the sibling SVG measures its DOM rectangle.
const image=new Image();let sourceW=1920,sourceH=1400;
image.onload=()=>{sourceW=image.naturalWidth;sourceH=image.naturalHeight;const c=$('frame-canvas');c.width=sourceW;c.height=sourceH;c.getContext('2d').drawImage(image,0,0);fitMedia()};image.onerror=()=>toast('Не найден assets/sample-frame.jpg. Открывайте макет вместе с папкой assets.');image.src='assets/sample-frame.jpg';
function fitMedia(){const stage=$('stage');const fit=Math.min(Math.max(1,stage.clientWidth-32)/sourceW,Math.max(1,stage.clientHeight-24)/sourceH);$('media-frame').style.width=sourceW*fit+'px';$('media-frame').style.height=sourceH*fit+'px';applyView()}
function applyView(){$('media-frame').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('zoom-value').textContent=Math.round(zoom*100)+'%';renderShapes()}
function renderShapes(){const stage=$('stage'),media=$('media-frame'),svg=$('annotation-layer');if(!stage||!media)return;const r=media.getBoundingClientRect(),s=stage.getBoundingClientRect();const left=r.left-s.left,top=r.top-s.top;svg.innerHTML=outlines?visibleShapes().map((b,i)=>{const x=left+b.x*r.width,y=top+b.y*r.height,w=b.w*r.width,h=b.h*r.height,col=classData[b.ci].color,on=i===selected;const label=`${String(b.id).padStart(2,'0')}  ${classData[b.ci].short}`;const labelW=label.length*7+16;const labelY=i===1?y+h+3:y-24;return `<g data-shape="${i}" class="${on?'selected':''}" aria-label="${esc(classData[b.ci].short)}"><rect class="box-halo" x="${x}" y="${y}" width="${w}" height="${h}"/><rect class="box-outline" x="${x}" y="${y}" width="${w}" height="${h}" stroke="${col}" ${b.hidden?'stroke-dasharray="7 5"':''}/><rect x="${x}" y="${labelY}" width="${labelW}" height="21" rx="3" fill="#17232F" stroke="${col}" stroke-width="1"/><text x="${x+7}" y="${labelY+14}" class="label-text">${label}</text>${on?[[x,y],[x+w,y],[x,y+h],[x+w,y+h]].map(([cx,cy])=>`<rect class="handle" x="${cx-3}" y="${cy-3}" width="6" height="6"/>`).join(''):''}</g>`}).join(''):'';svg.querySelectorAll('[data-shape]').forEach(g=>g.onpointerdown=e=>{if(tool==='select'){e.stopPropagation();pick(Number(g.dataset.shape))}})}
function zoomBy(factor,clientX,clientY){const s=$('stage').getBoundingClientRect();const px=(clientX??s.left+s.width/2)-(s.left+s.width/2),py=(clientY??s.top+s.height/2)-(s.top+s.height/2);const next=Math.max(1,Math.min(5,zoom*factor)),k=next/zoom;pan={x:px-k*(px-pan.x),y:py-k*(py-pan.y)};zoom=next;applyView()}
$('zoom-in').onclick=()=>zoomBy(1.25);$('zoom-out').onclick=()=>zoomBy(.8);$('fit').onclick=()=>{zoom=1;pan={x:0,y:0};fitMedia()};$('stage').addEventListener('wheel',e=>{e.preventDefault();zoomBy(e.deltaY<0?1.1:1/1.1,e.clientX,e.clientY)},{passive:false});new ResizeObserver(fitMedia).observe($('stage'));
$('toggle-labels').onclick=()=>{outlines=!outlines;$('toggle-labels').setAttribute('aria-pressed',String(outlines));renderShapes()};
let gesture=null;
function normalizedPoint(e){const r=$('media-frame').getBoundingClientRect();return {x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
$('stage').onpointerdown=e=>{if(e.button!==0||locked())return;const point=normalizedPoint(e);if(tool==='select'){gesture={kind:'pan',x:e.clientX,y:e.clientY,pan:{...pan}}}else if(['box','track'].includes(tool)&&point.x>=0&&point.x<=1&&point.y>=0&&point.y<=1){gesture={kind:'draw',point}}else if(tool==='polygon'){toast('В этом макете показано расположение инструмента контура. Рабочая логика полигонов остаётся в BoxCanvas.')}if(gesture)$('stage').setPointerCapture(e.pointerId)};
$('stage').onpointermove=e=>{if(!gesture)return;if(gesture.kind==='pan'){pan={x:gesture.pan.x+e.clientX-gesture.x,y:gesture.pan.y+e.clientY-gesture.y};applyView()}};
$('stage').onpointerup=e=>{if(gesture?.kind==='draw'){const p=normalizedPoint(e),a=gesture.point,b={x:Math.max(0,Math.min(1,p.x)),y:Math.max(0,Math.min(1,p.y))};if(Math.abs(a.x-b.x)>.01&&Math.abs(a.y-b.y)>.01){if(uiState==='empty'){$('state').value='ready';uiState='ready';shapes=[]}shapes.push({id:Math.max(0,...shapes.map(s=>s.id))+1,ci:activeClass,x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y),keys:[frame],interpolate:true,step:5,start:frame,end:LAST,hidden:false});selected=shapes.length-1;chooseTool('select');setTab('tracks');toast('Демонстрационная фигура добавлена. В макете все фигуры показаны в списке треков.')}}gesture=null};$('stage').onpointercancel=()=>gesture=null;
$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('help-dialog').open)return;const k=e.key.toLowerCase();const t={v:'select',b:'box',p:'polygon',t:'track',a:'auto'}[k];if(t){e.preventDefault();chooseTool(t)}else if(k==='0')$('fit').click();else if(k==='k')addKey();else if(k==='delete')deleteTrack();else if(k==='arrowleft'){e.preventDefault();setFrame(frame-1)}else if(k==='arrowright'){e.preventDefault();setFrame(frame+1)}else if(k===' '){e.preventDefault();if(tool==='auto')$('commit-auto').click();else togglePlay()}else if(k==='escape'){chooseTool('select')}else if(k==='?')$('help').click();else if(['1','2','3','4'].includes(k))chooseClass(Number(k)-1)});
renderClasses();renderObjects();fitMedia();
