const $=id=>document.getElementById(id);
function applyTheme(){document.body.dataset.style=styleId;lab.apply(lab.palettes.find(p=>p.id===paletteId));document.body.classList.toggle('clean',query.get('clean')==='1')}
function updateAddress(){const u=new URL(location.href);u.searchParams.set('style',styleId);u.searchParams.set('palette',paletteId);u.searchParams.set('screen',screenId);try{history.replaceState(null,'',u)}catch{}}
function navItem(id,label,code,count=''){const active=id===screenId||(id==='tasks'&&screenId==='task')||(id==='datasets'&&['dataset','import','classes'].includes(screenId))||(id==='augments'&&screenId==='graph')||(id==='training'&&['run','trainset','wizard'].includes(screenId));return `<a class="nav-link ${active?'active':''}" href="${route(id)}" ${active?'aria-current="page"':''}><span class="nav-code">${code}</span><span>${label}</span>${count?`<span class="nav-count">${count}</span>`:''}</a>`}
function controls(){return `<div class="lab-controls"><a href="index.html">← Направления</a><label>Стиль<select id="style-select">${lab.styles.map(s=>`<option value="${s.id}" ${s.id===styleId?'selected':''}>${s.name}</option>`).join('')}</select></label><label>Палитра<select id="palette-select">${lab.palettes.map(p=>`<option value="${p.id}" ${p.id===paletteId?'selected':''}>${p.name}</option>`).join('')}</select></label><label>Экран<select id="screen-select">${lab.screens.map(s=>`<option value="${s.id}" ${s.id===screenId?'selected':''}>${s.name}</option>`).join('')}</select></label><label>Состояние<select id="state-select"><option value="ready">Рабочее</option><option value="empty">Пустое</option><option value="loading">Загрузка</option><option value="error">Ошибка</option><option value="readonly">Просмотр</option></select></label><span class="lab-note">Данные примера</span><button id="clean">Без рамки</button></div>`}
function render(){applyTheme();const data=(screenContent[screenId]||screenContent.overview)();document.title=`${data.title||'Вход'} / ${lab.styles.find(s=>s.id===styleId).name} / макет`;let body=data.body;if(displayState==='empty')body=`<section class="empty-state"><h2>Здесь пока нет данных</h2><p>Экран «${lab.screens.find(s=>s.id===screenId).name}» в состоянии до начала работы. Основное действие остаётся доступным.</p>${data.actions||action('restore-state','Показать пример','primary')}</section>`;if(displayState==='loading')body=`<section class="panel" role="status"><h2>Загружаем данные</h2><p class="section-gap">Содержимое появится после получения ответа.</p><div class="loading-lines"><i style="--w:85%"></i><i style="--w:65%"></i><i style="--w:93%"></i><i style="--w:72%"></i></div></section>`;if(displayState==='error')body=`<section class="empty-state" role="alert"><h2>Не удалось загрузить данные</h2><p>Повторите запрос. Текущий раздел и выбранные параметры сохранены.</p>${action('restore-state','Повторить','primary')}</section>`;
$('app').innerHTML=controls()+`<div class="app-layout"><aside class="sidebar"><a class="wordmark" href="${route('projects')}"><span class="word-symbol">f</span>frame</a><nav class="nav-group" aria-label="Проекты"><span class="nav-caption">Рабочая среда</span>${navItem('projects','Проекты','ПР')}${navItem('overview','Обзор','ОБ')}${navItem('tasks','Таски','ТС','4')}${navItem('datasets','Датасеты','ДТ','1')}${navItem('classes','Классы','КЛ','26')}</nav><nav class="nav-group" aria-label="Инструменты"><span class="nav-caption">Подготовка и модель</span>${navItem('augments','Аугментации','АУ')}${navItem('training','Обучение','МО')}${navItem('hardware','Оборудование','GPU')}${navItem('members','Участники','УЧ')}</nav><div class="sidebar-bottom"><strong>Варан</strong>Исходные данные<br>6,9 ГБ на сервере</div></aside><header class="topbar"><a class="project-picker" href="${route('projects')}">${screenId==='projects'?'Рабочая среда':'Варан'} <span class="muted">⌄</span></a><span class="breadcrumb">${lab.screens.find(s=>s.id===screenId)?.name||'Обзор'}</span><span class="spacer"></span><a href="screens.html" class="muted">Все экраны</a><a class="account-link" href="${route('account')}"><span class="avatar">ЕМ</span><span>Елена Морозова</span></a></header><main class="main">${data.title?`<div class="page-head"><div>${data.eyebrow?`<p class="eyebrow">${data.eyebrow}</p>`:''}<h1>${data.title}</h1><p>${data.description}</p></div><div class="head-actions">${data.actions}</div></div>`:''}${displayState==='readonly'?'<div class="notice">Режим просмотра: изменение данных недоступно.</div>':''}<div id="screen-body">${body}</div><footer class="page-foot"><span>HTML-макет / демонстрационные данные / без записи на сервер</span><span>Компоновка редактора A сохранена</span></footer></main></div><dialog id="dialog"><div class="dialog-head"><h2 id="dialog-title"></h2><button id="dialog-close" type="button">Закрыть</button></div><div id="dialog-body"></div></dialog><div class="toast" id="toast" role="status" hidden></div>`;
$('state-select').value=displayState;bind();if(screenId==='graph'&&displayState==='ready')requestAnimationFrame(()=>{renderInspector();wireGraph();bindNodes()});if(displayState==='readonly'){document.querySelectorAll('#screen-body [data-action],.head-actions [data-action],#screen-body input[type=color]').forEach(e=>e.disabled=true)}
}
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4300)}
function modal(title,body){$('dialog-title').textContent=title;$('dialog-body').innerHTML=body;$('dialog').showModal();$('dialog-body').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action))}
function simpleForm(title,fields,onSubmit,submit='Сохранить в макете'){modal(title,`<form id="modal-form"><div class="form-grid">${fields}</div><p class="error-text" id="form-error" hidden></p><div class="form-actions"><button class="primary" type="submit">${submit}</button></div></form>`);$('modal-form').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}}
function done(message){$('dialog').close();toast(message)}
function bind(){
$('style-select').onchange=e=>{styleId=e.target.value;updateAddress();render()};$('palette-select').onchange=e=>{paletteId=e.target.value;updateAddress();render()};$('screen-select').onchange=e=>location.href=route(e.target.value);$('state-select').onchange=e=>{displayState=e.target.value;render()};$('clean').onclick=()=>{document.body.classList.add('clean');toast('F2 возвращает панель сравнения.')};$('dialog-close').onclick=()=>$('dialog').close();
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{demo.tab=b.dataset.tab;render()});document.querySelectorAll('[data-import-step]').forEach(b=>b.onclick=()=>{demo.importStep=Number(b.dataset.importStep);render()});document.querySelectorAll('[data-wizard-step]').forEach(b=>b.onclick=()=>{demo.wizardStep=Number(b.dataset.wizardStep);render()});
if($('search'))$('search').oninput=filterRows;for(const id of ['task-filter','group-filter'])if($(id))$(id).onchange=filterRows;
if($('split-filter'))$('split-filter').onchange=filterGallery;if($('unlabeled'))$('unlabeled').onchange=filterGallery;
if($('class-filter'))$('class-filter').onchange=()=>toast('Оба класса есть в демонстрационных кадрах.');
if($('frame-sort'))$('frame-sort').onchange=()=>{const g=$('gallery');[...g.children].reverse().forEach(el=>g.append(el))};
document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{$('gallery').classList.toggle('large',b.dataset.size==='l');document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('on',x===b))});
document.querySelectorAll('[data-color]').forEach(c=>c.oninput=()=>{demo.classRows[Number(c.dataset.color)][3]=c.value;c.closest('tr').querySelector('.color-dot').style.setProperty('--class-color',c.value)});
if($('auth-form'))$('auth-form').onsubmit=e=>{e.preventDefault();if(demo.auth==='register'){demo.auth='confirm';render()}else location.href=route('projects')};
if($('node-search'))$('node-search').oninput=e=>document.querySelectorAll('[data-node-add]').forEach(n=>n.hidden=!n.textContent.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelectorAll('[data-node-add]').forEach(b=>b.onclick=()=>{const id=String(demo.graphNodes.length);demo.graphNodes.push({id,title:b.dataset.nodeAdd,kind:'Преобразование',x:220,y:Math.min(350,60+demo.graphNodes.length*32)});demo.node=id;render();toast('Узел добавлен в макет. Соединения новых узлов здесь не редактируются.')});
if($('graph-version'))$('graph-version').onchange=e=>{const locked=e.target.selectedIndex>0;document.querySelectorAll('[data-node-add],[data-action="save-graph"]').forEach(b=>b.disabled=locked);$('graph-plane').dataset.locked=String(locked);renderInspector();toast(locked?'Старая версия: только просмотр.':'Открыта текущая версия.')};
}
function filterRows(){const q=$('search')?.value.toLowerCase()||'',status=$('task-filter')?.value,group=$('group-filter')?.value;document.querySelectorAll('[data-search-row]').forEach(row=>{const text=row.textContent.toLowerCase();row.hidden=!text.includes(q)||(status&&status!=='Все статусы'&&!text.includes(status.toLowerCase()))||(group&&group!=='Все группы'&&!text.includes(group.toLowerCase()))})}
function filterGallery(){let count=0;document.querySelectorAll('.frame-card').forEach(el=>{el.hidden=$('unlabeled').checked||($('split-filter').value!=='all'&&el.dataset.split!==$('split-filter').value);if(!el.hidden)count++});$('gallery-found').textContent=count?`${count} кадров в примере`:'Под условия не подходит ни один кадр';}
function handleAction(name){
if(name==='restore-state'){displayState='ready';render();return}
if(name==='create-project'){simpleForm('Новый проект',field('Название',input('name','','text','required maxlength="70"'))+field('Код',input('code','','text','placeholder="Необязательно"'))+field('Описание','<textarea name="description"></textarea>','',true),data=>{demo.extraProjects.push({name:data.get('name'),desc:data.get('description')||'Новый проект',frames:'0',classes:'0',state:'Черновик'});$('dialog').close();render();toast('Проект добавлен только в текущий макет.')},'Создать в макете');return}
if(name==='create-task'){simpleForm('Новая таска',field('Название',input('name','','text','required'))+field('Тип',select('type',['Видеоразметка','Кадры']))+field('Ответственный',select('owner',['Не назначен','Елена Морозова','Павел Лебедев'])),()=>done('Форма таски проверена. Серверное задание не создано.'));return}
if(name==='create-class'||name.startsWith('edit-class-')){const i=name==='create-class'?-1:Number(name.split('-').pop()),row=demo.classRows[i]||['',0,'Рабочие органы','#72bcff'];simpleForm(i<0?'Новый класс':'Редактирование класса',field('Название',input('name',row[0],'text','required'))+field('Группа',select('group',['Рабочие органы','Путевое хозяйство']))+field('Цвет',input('color',row[3],'color')),data=>{const item=[data.get('name'),row[1],data.get('group'),data.get('color')];if(i<0)demo.classRows.push(item);else demo.classRows[i]=item;$('dialog').close();render();toast('Класс изменён только в макете.')});return}
if(name==='create-group'){simpleForm('Новая группа',field('Название группы',input('name','','text','required'),'',true),()=>done('Группа задана в демонстрационной форме.'));return}
if(name==='invite'){simpleForm('Пригласить участника',field('Логин или почта',input('identity','','text','required'),'',true)+field('Роль',select('role',['Редактор','Просмотр','Администратор'])),()=>done('Предпросмотр приглашения готов. Сообщение никому не отправлено.'),'Проверить приглашение');return}
if(name==='export'){modal('Экспорт датасета',`<p>Выберите состав выгрузки. В макете файл не формируется.</p><div class="form-grid">${field('Формат',select('format',['YOLO / боксы','YOLO / контуры']))}${field('Данные',select('source',['Изображения и разметка','Только разметка']))}${field('Части',select('parts',['Все части','train','val','test']))}</div><div class="form-actions">${action('export-demo','Подготовить экспорт','primary')}</div>`);return}
if(name==='export-demo'){done('Параметры экспорта выбраны. Реальная выгрузка остаётся в приложении.');return}
if(name==='start-run'){simpleForm('Запуск обучения',field('Название',input('name','Варан / baseline-05','text','required'))+field('Модель',select('model',['YOLO / детекция','YOLO / сегментация']))+field('Эпохи',input('epochs','100','number','min="1" required'))+field('Размер изображения',input('imgsz','640','number','min="32" step="32" required'))+field('Batch size',input('batch','16','number','min="1" required'))+field('Устройство',select('gpu',['Автоматически','GPU 0','GPU 1']))+field('Аугментации',select('augmentation',['Из набора','Настройки YOLO','Без аугментаций'])),()=>{done('Показан запуск обучения. GPU и сервер не задействованы.')},'Проверить параметры');return}
if(name.startsWith('frame-')){const n=Number(name.split('-')[1]);modal('Кадр '+(n+1),`<img src="assets/frame-${n%8}.jpg" alt="Кадр из датасета Варан" style="display:block;width:100%;max-height:50dvh;object-fit:contain;background:var(--bg)"><p class="section-gap">Исходные пропорции сохранены. Откройте редактор A, чтобы сравнить оформление канваса и инспектора.</p><div class="form-actions">${link('editor','Открыть редактор A','button primary')}</div>`);return}
if(name==='toggle-boxes'){const hidden=document.body.classList.toggle('hide-boxes');document.querySelectorAll('.thumb-box').forEach(b=>b.hidden=hidden);const b=document.querySelector('[data-action="toggle-boxes"]');b.classList.toggle('on',!hidden);b.textContent=hidden?'Разметка выключена':'Разметка включена';return}
if(name==='task-status'){modal('Статус таски',`<div class="form-field">${select('status',['Новая','В работе','На проверке','Готова'])}</div><div class="form-actions">${action('status-commit','Применить в макете','primary')}</div>`);return}
if(name==='status-commit'){done('Статус выбран. Данные проекта не изменены.');return}
if(name==='import-next'||name==='import-back'){demo.importStep+=name==='import-next'?1:-1;demo.importStep=Math.max(0,Math.min(2,demo.importStep));render();return}
if(name==='wizard-next'||name==='wizard-back'){demo.wizardStep+=name==='wizard-next'?1:-1;demo.wizardStep=Math.max(0,Math.min(4,demo.wizardStep));render();return}
if(name==='skipped-files'){modal('Пропущенные файлы',table(['Файл','Причина'],[['.DS_Store','Служебный файл'],['__MACOSX/._data.yaml','Служебный файл'],['notes.txt','Не относится к датасету']]));return}
if(name==='gpu-limits'){simpleForm('Ограничения GPU',field('Резерв видеопамяти, ГБ',input('reserve','2','number','min="0" max="24"'))+field('Одновременных задач',input('jobs','2','number','min="1" max="8"')),()=>done('Лимиты показаны в макете. Настройки оборудования не менялись.'));return}
if(name==='change-password'){simpleForm('Изменить пароль',field('Текущий пароль',input('old','','password','required'),'',true)+field('Новый пароль',input('next','','password','required minlength="6"'))+field('Повторите пароль',input('repeat','','password','required minlength="6"')),data=>{if(data.get('next')!==data.get('repeat')){$('form-error').textContent='Пароли не совпадают.';$('form-error').hidden=false}else done('Форма проверена. Пароль учётной записи не менялся.')});return}
if(name.startsWith('auth-')){demo.auth=name.slice(5);render();return}
if(name==='logout'){location.href=route('login');return}
if(name==='create-graph'){simpleForm('Новый граф',field('Название',input('name','','text','required'),'',true),()=>{location.href=route('graph')},'Открыть пример графа');return}
const messages={'import-commit':'Импорт показан в макете. Архив и проект на сервере не изменены.','build-set':'Сборка показана в макете. Обучающий набор не создан.','save-graph':'Показано сохранение версии. Граф на сервере не менялся.','preview-graph':'Предпросмотр использует исходный кадр. Аугментации не вычисляются.','materialize':'Выгрузка кадров показана в макете. Исходные видео и таски не менялись.','close-annotation':'Закрытие разметки показано в макете. Реальный редактор остаётся доступен.','video-upload':'Загрузка видео предусмотрена в задаче. Этот макет не загружает файлы.','video-cut':'Нарезка на перегоны остаётся в задаче. Серверная операция не запускается.','weights':'Кнопка выгрузки весов предусмотрена. В макете нет файла модели.','stop-run':'Остановка показана в макете. Реальное обучение не останавливается.','queue-remove':'Удаление из очереди показано в макете. GPU-задачи не менялись.','delete-set':'Удаление набора показано в макете. Файлы не удалялись.','save-profile':'Профиль изменён только в демонстрационных полях.','friend-add':'Заявка показана в макете. Сообщения не отправляются.','friend-remove':'Удаление друга показано в макете. Контакты не менялись.','friend-accept':'Принятие заявки показано в макете. Контакты не менялись.','invite-accept':'Принятие приглашения показано в макете. Доступы не менялись.','invite-decline':'Отклонение приглашения показано в макете. Доступы не менялись.','page-prev':'В примере восемь кадров. Полная пагинация остаётся в приложении.','page-next':'В примере восемь кадров. Полная пагинация остаётся в приложении.','refresh':'Обновлены демонстрационные показатели. Соединения с GPU нет.'};toast(messages[name]||'Действие показано в макете. Данные проекта не изменены.');
}
function renderInspector(){const n=demo.graphNodes.find(n=>n.id===demo.node);if(!n||!$('node-inspector'))return;$('node-inspector').innerHTML=`<p class="eyebrow">${n.kind}</p><h3>${n.title}</h3>${n.kind==='Источник'?field('Источник',select('source',['Обучающая часть набора'])):n.kind==='Выход'?kv([['Формат','YOLO'],['Множитель','× 2,4']]):field('Вероятность',input('probability','0.7','number','min="0" max="1" step="0.05"'))+field('Интенсивность','<input type="range" min="0" max="100" value="35" aria-label="Интенсивность">')}<p class="section-gap">Исходный кадр</p><img src="assets/frame-0.jpg" alt="Исходный кадр для предпросмотра графа">`;$('node-inspector').querySelectorAll('input,select').forEach(el=>el.disabled=$('graph-plane').dataset.locked==='true')}
function wireGraph(){const plane=$('graph-plane');if(!plane)return;const pr=plane.getBoundingClientRect();const nodes=[...plane.querySelectorAll('[data-node]')];$('graph-wires').innerHTML=nodes.slice(0,2).map((el,i)=>{const a=el.getBoundingClientRect(),b=nodes[i+1].getBoundingClientRect();const x=a.left-pr.left+a.width/2,y=a.bottom-pr.top,x2=b.left-pr.left+b.width/2,y2=b.top-pr.top;return `<path d="M${x} ${y} C${x} ${y+40},${x2} ${y2-40},${x2} ${y2}"/>`}).join('')}
function bindNodes(){document.querySelectorAll('[data-node]').forEach(el=>{let drag=null;el.onpointerdown=e=>{demo.node=el.dataset.node;document.querySelectorAll('[data-node]').forEach(n=>n.classList.toggle('selected',n===el));renderInspector();if($('graph-plane').dataset.locked==='true')return;const node=demo.graphNodes.find(n=>n.id===demo.node);drag={x:e.clientX,y:e.clientY,left:node.x,top:node.y,node};el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!drag)return;const plane=$('graph-plane');drag.node.x=Math.max(0,Math.min(plane.clientWidth-el.offsetWidth,drag.left+e.clientX-drag.x));drag.node.y=Math.max(0,Math.min(plane.clientHeight-el.offsetHeight,drag.top+e.clientY-drag.y));el.style.left=drag.node.x+'px';el.style.top=drag.node.y+'px';wireGraph()};el.onpointerup=()=>drag=null;el.onpointercancel=()=>drag=null})}
window.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();document.body.classList.toggle('clean')}});window.addEventListener('resize',wireGraph);
render();
